# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    working-directory: client

env:
    CI: ""

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
        cache-dependency-path: client/package-lock.json
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

    - name: Get date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H')"

    - name: Upload build folder as artifact
      uses: actions/upload-artifact@v3
      with:
        name: LJEP-FRONTEND-${{ steps.date.outputs.date }}
        path: ${{ github.workspace }}/client/build/
