name: Node Build

env:
  ZIP_NAME: frontend
  CI: "false"

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]
  workflow_dispatch:

defaults:
  run:
    working-directory: client

jobs:
  Node-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
        cache-dependency-path: client/package-lock.json
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

    - name: Upload build folder as artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.ZIP_NAME }}
        path: ${{ github.workspace }}/client/build/
