name: Test

env:
  NODE_VER: 16.x

  FRONTEND_REPO_DIR: client
  BACKEND_REPO_DIR: server


on:
  push:
    branches: [ main, release ]
  pull_request:
    branches: [ main, release ]
  workflow_dispatch:


jobs:
  Frontend-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.FRONTEND_REPO_DIR }}
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VER }}
        cache: 'npm'
        cache-dependency-path: ${{ github.workspace }}/${{ env.FRONTEND_REPO_DIR }}/package-lock.json

    - run: npm ci
    - run: npm test
